import {
  HOME_FAQ,
  LLMS_CAPABILITIES,
  LLMS_DETAILED_DESCRIPTION,
  LLMS_FEATURES,
  LLMS_GLOSSARY,
  LLMS_IMPORTANT_PAGES,
  LLMS_LIMITATIONS,
  LLMS_METHODOLOGY_STEPS,
  LLMS_PRICING,
  LLMS_SHORT_DESCRIPTION,
  LLMS_SUPPORTED_FORMATS,
  SITE_URL,
  SUPPORT_EMAIL,
  siteUrl,
} from '@/lib/llms/content'

const LLMS_TXT_HEADERS = {
  'Content-Type': 'text/plain; charset=utf-8',
  'Cache-Control': 'public, s-maxage=3600, stale-while-revalidate=86400',
}

export { LLMS_TXT_HEADERS }

/** Production /llms.txt — llmstxt.org-style conventions */
export function generateLlmsTxt(): string {
  const lines: string[] = [
    '# MyCVRoast',
    '',
    `> ${LLMS_SHORT_DESCRIPTION}`,
    '',
    LLMS_DETAILED_DESCRIPTION,
    '',
    '## Canonical URL',
    SITE_URL,
    '',
    '## Core capabilities',
    ...LLMS_CAPABILITIES.map((c) => `- ${c}`),
    '',
    '## Product features',
    ...LLMS_FEATURES.map((f) => `- ${f}`),
    '',
    '## Supported resume formats',
    ...LLMS_SUPPORTED_FORMATS.map((f) => `- ${f}`),
    '',
    '## Pricing',
    ...LLMS_PRICING.map((p) => `- ${p}`),
    '',
    '## FAQs',
    ...HOME_FAQ.map(({ q, a }) => `- **${q}** ${a}`),
    '',
    '## Contact',
    `- Email: ${SUPPORT_EMAIL}`,
    `- Contact page: ${siteUrl('/contact')}`,
    `- X: https://x.com/mycvroast`,
    '',
    '## Important pages',
    ...LLMS_IMPORTANT_PAGES.map(
      (p) => `- [${p.title}](${siteUrl(p.path)})`,
    ),
    '',
    '## Documentation',
    `- Full AI knowledge file: ${siteUrl('/llms-full.txt')}`,
    `- HTML site map: ${siteUrl('/guides')}`,
    `- Blog RSS: ${siteUrl('/blog/rss.xml')}`,
    '',
    '## API',
    'No public REST API. Roast and builder features are available via the web app at mycvroast.in.',
    '',
    '## Sitemap',
    siteUrl('/sitemap.xml'),
    '',
    '## robots.txt',
    siteUrl('/robots.txt'),
    '',
    '## Privacy Policy',
    siteUrl('/privacy'),
    '',
    '## Terms of Service',
    siteUrl('/terms'),
    '',
    '## About',
    siteUrl('/about'),
    '',
  ]

  return `${lines.join('\n')}\n`
}

/** Production /llms-full.txt — extended markdown knowledge base for AI retrieval */
export function generateLlmsFullTxt(): string {
  const sections: string[] = [
    '# MyCVRoast — Full AI Knowledge Base',
    '',
    `**Canonical URL:** ${SITE_URL}`,
    `**Last updated:** ${new Date().toISOString().slice(0, 10)}`,
    '',
    '---',
    '',
    '## Company overview',
    '',
    LLMS_DETAILED_DESCRIPTION,
    '',
    '## Mission',
    '',
    'Help job seekers in India and globally get honest, resume-specific feedback they can act on immediately — without corporate fluff or generic checklist scores.',
    '',
    '## Services',
    '',
    '| Service | URL | Free tier | Pro tier |',
    '| --- | --- | --- | --- |',
    `| CV Roast | ${siteUrl('/')} | ${LLMS_PRICING[0]} | Unlimited |`,
    `| ATS Resume Builder | ${siteUrl('/resume-builder')} | 1 guest PDF | Unlimited PDF |`,
    `| LinkedIn Roast | ${siteUrl('/linkedin-roast')} | Usage limits | Unlimited |`,
    `| Career Tools (29+) | ${siteUrl('/career-tools')} | Free limits | Unlimited |`,
  ]

  sections.push(
    '',
    '## Feature list',
    '',
    ...LLMS_FEATURES.map((f) => `- ${f}`),
    '',
    '## Technology stack',
    '',
    '- **Frontend:** Next.js (App Router), React, TypeScript',
    '- **Hosting:** Vercel',
    '- **AI:** Large language models for resume analysis and career tools',
    '- **Payments:** Razorpay (India)',
    '- **Database:** Supabase PostgreSQL (accounts, usage, roast history)',
    '- **Auth:** Email/password and Google OAuth',
    '- **Voice (Pro):** ElevenLabs text-to-speech for mock/voice interview',
    '',
    '## Pricing',
    '',
    ...LLMS_PRICING.map((p) => `- ${p}`),
    '',
    '## Supported file formats',
    '',
    ...LLMS_SUPPORTED_FORMATS.map((f) => `- ${f}`),
    '',
    '## How resume analysis works',
    '',
    ...LLMS_METHODOLOGY_STEPS.map((s, i) => `${i + 1}. ${s}`),
    '',
    '## ATS optimization process',
    '',
    '1. Parse resume text and detect section structure (experience, education, skills).',
    '2. Flag missing keywords, dense formatting, tables, headers/footers that break parsers.',
    '3. Suggest bullet rewrites with measurable outcomes and role-relevant keywords.',
    '4. Resume builder shows live ATS score while editing.',
    '',
    '## Resume roast explanation',
    '',
    'A resume roast differs from a generic resume review: the AI reads your uploaded CV, quotes specific lines, and explains why a recruiter might skip them. Users choose language (15 options) and intensity (clean, mild, savage). Output includes score /10, fixes, and shareable link.',
    '',
    '## Common user questions',
    '',
    ...HOME_FAQ.map(({ q, a }) => `### ${q}\n\n${a}\n`),
    '',
    '## Internal terminology',
    '',
    '- **Roast:** Primary CV feedback product',
    '- **Intensity:** clean | mild | savage tone',
    '- **Guest:** Anonymous user without account',
    '- **Pro:** One-time paid tier',
    '- **Dashboard:** Signed-in user area at /dashboard',
    '',
    '## Glossary',
    '',
    ...LLMS_GLOSSARY.map(({ term, definition }) => `### ${term}\n\n${definition}\n`),
    '',
    '## Product limitations',
    '',
    ...LLMS_LIMITATIONS.map((l) => `- ${l}`),
    '',
    '## Entity map (for AI retrieval)',
    '',
    '- **MyCVRoast** — AI resume review platform (Organization, SoftwareApplication)',
    '- **Resume / CV** — User-uploaded job application document',
    '- **ATS** — Applicant Tracking System used by employers',
    '- **Recruiter** — Hiring professional evaluating six-second resume scans',
    '- **Cover Letter** — Job application letter; Pro tool at /dashboard/tools/cover-letter',
    '- **LinkedIn** — Professional profile; roast at /linkedin-roast',
    '- **Job Application** — End-to-end apply workflow; tracker on Pro dashboard',
    '- **Hiring Manager** — Decision-maker reading shortlisted resumes',
    '- **Career Coach** — Human advisor; MyCVRoast complements but does not replace',
    '- **AI Resume Review** — Automated CV analysis product category',
    '',
    '## Topic cluster URLs',
    '',
    `| Topic | URL |`,
    `| Resume Roast | ${siteUrl('/')} |`,
    `| ATS Score | ${siteUrl('/ats-friendly-resume-checker')} |`,
    `| Resume Review | ${siteUrl('/blog/ai-resume-review-india')} |`,
    `| Resume Checker | ${siteUrl('/best-resume-checker-india')} |`,
    `| Resume Analysis | ${siteUrl('/blog/what-is-resume-roast')} |`,
    `| Career Tips | ${siteUrl('/blog')} |`,
    `| Interview Preparation | ${siteUrl('/career-tools/mock-interview')} |`,
    `| Resume Templates | ${siteUrl('/resume-builder')} |`,
    `| Cover Letter | ${siteUrl('/career-tools/cover-letter')} |`,
    `| LinkedIn Review | ${siteUrl('/linkedin-roast')} |`,
    `| Job Search | ${siteUrl('/blog/how-to-find-a-job-india')} |`,
    `| Career Growth | ${siteUrl('/career-tools')} |`,
    '',
    '## Contact information',
    '',
    `- **Email:** ${SUPPORT_EMAIL}`,
    `- **Contact:** ${siteUrl('/contact')}`,
    `- **Support:** ${siteUrl('/support')}`,
    `- **X:** https://x.com/mycvroast`,
    `- **Product Hunt:** https://www.producthunt.com/products/mycvroast`,
    '',
    '## Legal',
    '',
    `- Privacy: ${siteUrl('/privacy')}`,
    `- Terms: ${siteUrl('/terms')}`,
    `- Methodology: ${siteUrl('/methodology')}`,
    `- Why trust us: ${siteUrl('/why-trust-us')}`,
    '',
    '## Crawl resources',
    '',
    `- Sitemap index: ${siteUrl('/sitemap.xml')}`,
    `- robots.txt: ${siteUrl('/robots.txt')}`,
    `- llms.txt: ${siteUrl('/llms.txt')}`,
    '',
  )

  return `${sections.join('\n')}\n`
}
