import Link from 'next/link'
import { pageMetadata } from '@/lib/seo'
import { SUPPORT_EMAIL, SUPPORT_MAILTO } from '@/lib/support'
import { SiteFooter } from '@/components/SiteFooter'
import { SiteHeader } from '@/components/SiteHeader'

export const metadata = pageMetadata({
  title: 'Terms of Service | MyCVRoast',
  description: 'Terms of use for MyCVRoast AI resume roaster, resume builder, and Pro plans.',
  path: '/terms',
})

export default function TermsPage() {
  return (
    <main className="min-h-screen flex flex-col bg-page">
      <SiteHeader activePath="home" breadcrumb="Terms" />
      <article className="flex-1 max-w-3xl mx-auto px-4 md:px-8 py-10 md:py-14 font-body text-sm text-dim leading-relaxed">
        <h1 className="font-display text-3xl text-white mb-6">Terms of Service</h1>
        <p className="mb-4 text-muted">Last updated: June 27, 2026</p>

        <section className="space-y-4">
          <h2 className="font-display text-lg text-white">Service</h2>
          <p>
            MyCVRoast provides AI-generated resume feedback for entertainment and educational
            purposes. Roasts are opinions generated by AI — not professional career counselling or
            legal advice.
          </p>

          <h2 className="font-display text-lg text-white">Acceptable use</h2>
          <p>
            Do not upload content you do not have rights to, attempt to abuse free limits, scrape
            the service, or use outputs to harass others. We may rate-limit or block abusive traffic.
          </p>

          <h2 className="font-display text-lg text-white">Pro plan</h2>
          <p>
            Pro is a one-time purchase for extended usage on your account or device fingerprint.
            Refunds are handled case-by-case — email{' '}
            <a href={SUPPORT_MAILTO} className="text-ember">
              {SUPPORT_EMAIL}
            </a>{' '}
            within 7 days if something went wrong.
          </p>

          <h2 className="font-display text-lg text-white">Disclaimer</h2>
          <p>
            AI output may be inaccurate, offensive, or incomplete. Use your judgment before sharing
            roasts publicly. We are not liable for hiring outcomes or emotional damage (Burnol not
            included).
          </p>

          <h2 className="font-display text-lg text-white">Changes</h2>
          <p>
            We may update these terms. Continued use after changes means acceptance. See also our{' '}
            <Link href="/privacy" className="text-ember">
              Privacy Policy
            </Link>
            .
          </p>
        </section>
      </article>
      <SiteFooter cinematic={false} />
    </main>
  )
}
