import {
  DASHBOARD_TOOLS,
  TOOL_CATEGORIES,
  toolAccessFreeLabel,
  toolAccessProLabel,
  type ToolSlug,
} from '@/lib/tools/dashboard/config'

export type CareerToolDemoVariant = 'interview' | 'form' | 'email' | 'analysis' | 'default'

export type CareerToolMarketing = {
  slug: ToolSlug
  headline: string
  tagline: string
  whatItDoes: string
  howItWorks: string[]
  whoItsFor: string
  inputLabel: string
  outputLabel: string
  exampleOutput: string
  freeVsPro: string
  dashboardHref: string
  seoTitle: string
  seoDescription: string
  keywords: string[]
  relatedSlugs: ToolSlug[]
  relatedBlogSlugs: string[]
  demoVariant: CareerToolDemoVariant
  categoryId: string
}

const CONTENT: Partial<
  Record<
    ToolSlug,
    Omit<CareerToolMarketing, 'slug' | 'dashboardHref' | 'freeVsPro' | 'categoryId'> & {
      categoryId?: string
    }
  >
> = {
  'mock-interview': {
    headline: 'AI Mock Interview with Voice',
    tagline: 'Practice with a real interviewer — not a chatbot form.',
    whatItDoes:
      'MyCVRoast reads your CV, picks questions for your target role, and runs a live mock interview. The AI interviewer speaks each question in a natural voice, you type or speak answers, and get a scored debrief at the end.',
    howItWorks: [
      'Paste or upload your CV and choose target role + interview style.',
      'Start the session — the AI interviewer asks questions one at a time.',
      'Answer by typing or speaking; voice mode auto-submits when you pause.',
      'Receive an overall score plus per-question feedback and sample answer frameworks.',
    ],
    whoItsFor: 'Job seekers preparing for HR, technical, or FAANG-style rounds who want realistic practice before the real call.',
    inputLabel: 'Your CV + target role',
    outputLabel: 'Scored mock interview with feedback',
    exampleOutput:
      'Overall 7/10 — strong STAR examples on leadership; tighten metrics on project impact. Sample framework provided for "Tell me about a conflict at work."',
    seoTitle: 'AI Mock Interview India — Practice with Voice | MyCVRoast',
    seoDescription:
      'Practice job interviews with an AI interviewer that reads your CV. Voice + text answers, natural speech, scored feedback. Pro tool on MyCVRoast.',
    keywords: ['mock interview ai', 'ai mock interview india', 'practice interview online', 'voice mock interview'],
    relatedSlugs: ['voice-interview', 'interview-prep', 'debrief'],
    relatedBlogSlugs: ['ai-mock-interview-tool', 'best-mock-interview-ai-india-2026'],
    demoVariant: 'interview',
    categoryId: 'interview',
  },
  'voice-interview': {
    headline: 'Voice Mock Interview',
    tagline: 'Speak your answers — get delivery + content feedback.',
    whatItDoes:
      'Same AI interviewer as text mode, but you answer out loud. Live transcription tracks words, fillers, and pace. AI scores both what you said and how you said it.',
    howItWorks: [
      'Set up role, style, and session length from your saved CV.',
      'Listen to each question (optional voice playback).',
      'Record your spoken answer — see live transcript and filler count.',
      'Submit and get instant feedback; full speech pattern report at the end.',
    ],
    whoItsFor: 'Candidates who want to fix "um", rambling answers, or nervous delivery before phone/video screens.',
    inputLabel: 'Spoken answers + your CV',
    outputLabel: 'Content score + speech pattern report',
    exampleOutput:
      'Content 8/10 — good structure. Delivery: 12 filler words; try pausing instead of "like". Longest answer: 142 words on system design.',
    seoTitle: 'Voice Mock Interview — Speak & Get Feedback | MyCVRoast',
    seoDescription:
      'Practice interviews by speaking your answers. Live transcription, filler detection, and AI feedback on content and delivery.',
    keywords: ['voice mock interview', 'speak interview practice', 'interview filler words'],
    relatedSlugs: ['mock-interview', 'interview-prep', 'elevator-pitch'],
    relatedBlogSlugs: ['voice-mock-interview-tool'],
    demoVariant: 'interview',
    categoryId: 'interview',
  },
  'interview-prep': {
    headline: 'Interview Question Coach',
    tagline: 'Questions they will ask YOU — from your CV.',
    whatItDoes:
      'Generates a personalised question list based on your CV, target role, and company. Pick behavioural, technical, CV-specific, or situational types — not generic Google lists.',
    howItWorks: [
      'Confirm your CV is loaded in the dashboard.',
      'Enter job title and optional company name.',
      'Select question types (behavioural, technical, etc.).',
      'Get a structured markdown list with why each question matters and how to prep.',
    ],
    whoItsFor: 'Anyone with an interview scheduled who wants a focused prep list tied to their actual experience.',
    inputLabel: 'CV + job title + company',
    outputLabel: 'Personalised question list with prep notes',
    exampleOutput:
      '15 questions for Product Manager @ Swiggy — including "Walk me through the retention experiment on your CV" and "How would you prioritise a backlog with eng constraints?"',
    seoTitle: 'AI Interview Prep Questions from Your CV | MyCVRoast',
    seoDescription:
      'Generate interview questions tailored to your CV and target role. Behavioural, technical, and CV-specific prep for Indian job seekers.',
    keywords: ['interview prep questions', 'ai interview prep', 'cv based interview questions'],
    relatedSlugs: ['mock-interview', 'debrief', 'skills-gap'],
    relatedBlogSlugs: ['ai-interview-prep-questions'],
    demoVariant: 'form',
    categoryId: 'interview',
  },
  debrief: {
    headline: 'Interview Debrief',
    tagline: 'Turn a rough interview into lessons learned.',
    whatItDoes:
      'Paste what happened in your interview — questions asked, how you answered, what felt off. AI gives honest feedback and a prep plan for next time.',
    howItWorks: [
      'Describe the interview (questions, your answers, vibe).',
      'AI analyses gaps vs your CV and the role.',
      'Get strengths, misses, and concrete fixes before the next round.',
    ],
    whoItsFor: 'Anyone who just finished a round and wants structured reflection instead of overthinking alone.',
    inputLabel: 'Interview notes or transcript',
    outputLabel: 'Debrief report + action items',
    exampleOutput:
      'You undersold the metrics project — rewrite that bullet. Prepare a cleaner answer for "Why leaving current role." Follow-up thank-you draft included.',
    seoTitle: 'Interview Debrief Tool — Free | MyCVRoast',
    seoDescription: 'Free AI interview debrief. Paste what happened, get feedback and next-step prep.',
    keywords: ['interview debrief', 'post interview feedback'],
    relatedSlugs: ['interview-prep', 'thank-you', 'mock-interview'],
    relatedBlogSlugs: [],
    demoVariant: 'analysis',
    categoryId: 'interview',
  },
  'jd-match': {
    headline: 'Job Description Matcher',
    tagline: 'See how your CV stacks up before you apply.',
    whatItDoes: 'Compares your CV against a job description and shows match score, missing keywords, and bullet tweaks to improve ATS pass rate.',
    howItWorks: ['Paste JD text and confirm CV.', 'AI scores fit and lists gaps.', 'Get rewritten bullets aligned to the role.'],
    whoItsFor: 'Applicants tailoring each application instead of spray-and-pray.',
    inputLabel: 'CV + job description',
    outputLabel: 'Match score + gap analysis + suggestions',
    exampleOutput: '72% match — missing Kubernetes, stakeholder management. Suggested bullet rewrite for backend role.',
    seoTitle: 'JD Match — CV vs Job Description Score | MyCVRoast',
    seoDescription: 'Match your CV to any job description. ATS keyword gaps and bullet suggestions for Indian roles.',
    keywords: ['jd match resume', 'cv job description match', 'ats keyword checker'],
    relatedSlugs: ['skills-gap', 'cover-letter', 'cv-rewriter'],
    relatedBlogSlugs: [],
    demoVariant: 'analysis',
    categoryId: 'apply',
  },
  'cover-letter': {
    headline: 'Cover Letter Generator',
    tagline: 'One letter that references YOUR CV — not a template.',
    whatItDoes: 'Writes a tailored cover letter using your CV bullets and the job description in a professional tone.',
    howItWorks: ['Add JD + role details.', 'AI drafts letter linking your proof points.', 'Edit, copy, or download as text.'],
    whoItsFor: 'Candidates who need a strong cover letter fast without generic ChatGPT fluff.',
    inputLabel: 'CV + job details',
    outputLabel: 'Tailored cover letter',
    exampleOutput: 'Three-paragraph letter referencing your 40% cost reduction project and why it maps to the hiring team\'s cloud migration mandate.',
    seoTitle: 'AI Cover Letter from Your CV | MyCVRoast',
    seoDescription: 'Generate cover letters tied to your CV and job description. Free tier available.',
    keywords: ['cover letter generator', 'ai cover letter india'],
    relatedSlugs: ['jd-match', 'cold-email', 'referral'],
    relatedBlogSlugs: ['cover-letter-for-resume-guide'],
    demoVariant: 'email',
    categoryId: 'apply',
  },
  'cold-email': {
    headline: 'Cold Email to Recruiters',
    tagline: 'Short outreach that gets replies.',
    whatItDoes: 'Drafts concise cold emails to hiring managers or recruiters using your CV highlights and target company.',
    howItWorks: ['Enter company, role, and contact context.', 'AI writes a 3–5 sentence email with a clear ask.', 'Copy and send from your inbox.'],
    whoItsFor: 'Pro users doing targeted outreach beyond job portals.',
    inputLabel: 'CV + company + role',
    outputLabel: 'Ready-to-send cold email',
    exampleOutput: 'Subject: Backend engineer — 3 yrs fintech, open to chat? Body ties your payment API work to their job post.',
    seoTitle: 'Cold Email to Recruiter — AI Draft | MyCVRoast',
    seoDescription: 'Pro cold email generator for job outreach in India. CV-aware, recruiter-friendly tone.',
    keywords: ['cold email recruiter', 'job outreach email'],
    relatedSlugs: ['referral', 'linkedin', 'cover-letter'],
    relatedBlogSlugs: [],
    demoVariant: 'email',
    categoryId: 'apply',
  },
  referral: {
    headline: 'Referral Request Message',
    tagline: 'Ask for a referral without being awkward.',
    whatItDoes: 'Creates a polite referral ask message for LinkedIn or email, referencing mutual context and your fit.',
    howItWorks: ['Name the contact, company, and role.', 'AI drafts a warm, specific ask.', 'Send on LinkedIn or email.'],
    whoItsFor: 'Networkers targeting referrals at target companies.',
    inputLabel: 'CV + contact + role',
    outputLabel: 'Referral request message',
    exampleOutput: 'Hi Priya — saw the PM opening at Razorpay. My payments background at X maps well; would you be open to referring?',
    seoTitle: 'Referral Ask Message Generator | MyCVRoast',
    seoDescription: 'Pro tool to draft referral requests for Indian job seekers.',
    keywords: ['referral message template', 'ask for referral linkedin'],
    relatedSlugs: ['cold-email', 'linkedin', 'cover-letter'],
    relatedBlogSlugs: [],
    demoVariant: 'email',
    categoryId: 'apply',
  },
  linkedin: {
    headline: 'LinkedIn Post & About Writer',
    tagline: 'Sound credible — not cringe.',
    whatItDoes: 'Turns CV highlights into LinkedIn About sections or short posts for job search visibility.',
    howItWorks: ['Pick post type or About rewrite.', 'AI uses your CV facts.', 'Copy to LinkedIn.'],
    whoItsFor: 'Job seekers building presence while applying.',
    inputLabel: 'CV + topic or goal',
    outputLabel: 'LinkedIn copy',
    exampleOutput: 'About section opening with your stack + impact metric; optional "Open to work" post draft.',
    seoTitle: 'LinkedIn Writer from CV | MyCVRoast',
    seoDescription: 'Generate LinkedIn About and posts from your resume. Free daily limit.',
    keywords: ['linkedin about generator', 'linkedin post job search'],
    relatedSlugs: ['linkedin-audit', 'freelancer-profile'],
    relatedBlogSlugs: ['linkedin-profile-optimization'],
    demoVariant: 'form',
    categoryId: 'linkedin',
  },
  'linkedin-audit': {
    headline: 'LinkedIn Profile Audit',
    tagline: 'Roast your profile like your CV.',
    whatItDoes: 'Scores your LinkedIn headline, About, and experience for recruiter search and gives fix list.',
    howItWorks: ['Paste profile sections.', 'Get audit score and prioritized fixes.', 'Apply on LinkedIn.'],
    whoItsFor: 'Candidates whose CV is strong but LinkedIn is neglected.',
    inputLabel: 'LinkedIn profile text',
    outputLabel: 'Audit score + fix list',
    exampleOutput: 'Headline too generic — lead with role + niche. About missing metrics; add 2 proof bullets from CV.',
    seoTitle: 'LinkedIn Profile Audit AI | MyCVRoast',
    seoDescription: 'Pro LinkedIn audit with actionable fixes for Indian professionals.',
    keywords: ['linkedin audit', 'linkedin profile review'],
    relatedSlugs: ['linkedin', 'cv-rewriter'],
    relatedBlogSlugs: [],
    demoVariant: 'analysis',
    categoryId: 'linkedin',
  },
  'cv-rewriter': {
    headline: 'Bullet Rewriter',
    tagline: 'Weak bullet → quantified, ATS-ready line.',
    whatItDoes: 'Rewrites resume bullets with action verbs, metrics, and clarity while keeping your facts honest.',
    howItWorks: ['Paste a bullet or experience block.', 'AI returns improved versions.', 'Paste into builder or CV.'],
    whoItsFor: 'Anyone fixing roast feedback or upgrading experience lines.',
    inputLabel: 'Resume bullet text',
    outputLabel: 'Improved bullet variants',
    exampleOutput: '"Managed team" → "Led 4-person squad shipping checkout revamp, cutting cart drop-off 18% in Q2."',
    seoTitle: 'Resume Bullet Rewriter AI | MyCVRoast',
    seoDescription: 'Free AI bullet rewriter for Indian resumes. Quantified, ATS-friendly lines.',
    keywords: ['resume bullet rewriter', 'cv bullet improvement'],
    relatedSlugs: ['skills-gap', 'compress', 'bias-check'],
    relatedBlogSlugs: ['resume-action-verbs'],
    demoVariant: 'form',
    categoryId: 'cv',
  },
  'skills-gap': {
    headline: 'Skills Gap Analysis',
    tagline: 'Know what to learn before you apply.',
    whatItDoes: 'Compares your CV skills to a target role and lists gaps, nice-to-haves, and learning priorities.',
    howItWorks: ['Enter target role or paste JD.', 'AI maps your skills vs requirements.', 'Get ranked gap list.'],
    whoItsFor: 'Career switchers and freshers planning upskilling.',
    inputLabel: 'CV + target role',
    outputLabel: 'Skills gap report',
    exampleOutput: 'Missing: SQL joins, A/B testing. Have: Python, dashboards. Priority: take a SQL course before analytics apps.',
    seoTitle: 'Skills Gap Analysis for Your CV | MyCVRoast',
    seoDescription: 'Free skills gap tool — compare CV to job role and plan learning.',
    keywords: ['skills gap analysis', 'resume skills checker'],
    relatedSlugs: ['jd-match', 'career-path', 'cv-rewriter'],
    relatedBlogSlugs: ['resume-skills-section'],
    demoVariant: 'analysis',
    categoryId: 'cv',
  },
  'gap-explainer': {
    headline: 'Career Gap Explainer',
    tagline: 'Honest script for resume gaps.',
    whatItDoes: 'Helps you explain employment gaps on CV or in interviews without oversharing or sounding defensive.',
    howItWorks: ['Describe the gap period briefly.', 'AI drafts CV line + interview talking points.', 'Use in applications.'],
    whoItsFor: 'Candidates with education, health, or job-search gaps.',
    inputLabel: 'Gap context',
    outputLabel: 'CV wording + interview script',
    exampleOutput: 'One-line CV note + 30-second interview answer focusing on upskilling during gap.',
    seoTitle: 'Explain Career Gap on Resume | MyCVRoast',
    seoDescription: 'Free career gap explainer for CV and interviews.',
    keywords: ['career gap resume', 'explain employment gap'],
    relatedSlugs: ['cv-rewriter', 'interview-prep'],
    relatedBlogSlugs: [],
    demoVariant: 'form',
    categoryId: 'cv',
  },
  compress: {
    headline: '1-Page CV Compressor',
    tagline: 'Fit more impact on one page.',
    whatItDoes: 'Condenses an overlong CV to one page while preserving strongest proof points.',
    howItWorks: ['Paste full CV text.', 'AI trims redundancy and tightens bullets.', 'Download condensed version.'],
    whoItsFor: 'Experienced hires hitting two-page bloat.',
    inputLabel: 'Full CV text',
    outputLabel: 'One-page condensed CV',
    exampleOutput: 'Reduced 620 words to 480 while keeping top 3 roles and metrics.',
    seoTitle: 'One Page Resume Compressor | MyCVRoast',
    seoDescription: 'Pro tool to compress CV to one page without losing impact.',
    keywords: ['one page resume', 'compress cv'],
    relatedSlugs: ['cv-rewriter', 'bias-check'],
    relatedBlogSlugs: ['one-page-resume-guide'],
    demoVariant: 'form',
    categoryId: 'cv',
  },
  'cv-localise': {
    headline: 'CV Localiser',
    tagline: 'Adapt your CV for US, UK, EU, or UAE norms.',
    whatItDoes: 'Rewrites format, spelling, and cultural cues for target country hiring expectations.',
    howItWorks: ['Pick target region.', 'AI localises CV structure and phrasing.', 'Export text.'],
    whoItsFor: 'Indians applying abroad or to MNC regional offices.',
    inputLabel: 'CV + target country',
    outputLabel: 'Localised CV',
    exampleOutput: 'UK-style personal statement, DD/MM dates, removed photo line, adjusted degree naming.',
    seoTitle: 'CV Localiser for International Jobs | MyCVRoast',
    seoDescription: 'Pro CV localisation for US, UK, EU, UAE applications.',
    keywords: ['international cv format', 'resume localisation'],
    relatedSlugs: ['cv-rewriter', 'cover-letter'],
    relatedBlogSlugs: [],
    demoVariant: 'form',
    categoryId: 'cv',
  },
  'bias-check': {
    headline: 'Bias & Fair Wording Check',
    tagline: 'Catch risky phrasing before recruiters do.',
    whatItDoes: 'Flags age, gender, caste, or exclusionary language in CV bullets and suggests neutral alternatives.',
    howItWorks: ['Paste CV section.', 'AI flags bias risks.', 'Apply suggested rewrites.'],
    whoItsFor: 'Inclusive hiring-conscious applicants and HR-minded editors.',
    inputLabel: 'CV text',
    outputLabel: 'Bias report + fixes',
    exampleOutput: 'Flag: "young energetic team" → suggest "collaborative cross-functional team."',
    seoTitle: 'Resume Bias Checker — Free | MyCVRoast',
    seoDescription: 'Free bias and fair wording check for Indian CVs.',
    keywords: ['resume bias check', 'inclusive cv language'],
    relatedSlugs: ['cv-rewriter', 'compress'],
    relatedBlogSlugs: [],
    demoVariant: 'analysis',
    categoryId: 'cv',
  },
  salary: {
    headline: 'Salary Negotiation Script',
    tagline: 'Know what to say when they ask your expectation.',
    whatItDoes: 'Builds negotiation talking points from your CV, role, location, and market context for Indian offers.',
    howItWorks: ['Enter role, current CTC, offer details.', 'AI drafts scripts for HR calls.', 'Practice before the call.'],
    whoItsFor: 'Candidates at offer stage who undervalue themselves.',
    inputLabel: 'CV + offer context',
    outputLabel: 'Negotiation scripts',
    exampleOutput: 'Opening anchor at 18 LPA with 3 proof points from CV; counter script if they cite "budget."',
    seoTitle: 'Salary Negotiation Script India | MyCVRoast',
    seoDescription: 'Pro salary negotiation scripts tailored to your CV and offer.',
    keywords: ['salary negotiation india', 'ctc negotiation script'],
    relatedSlugs: ['offer-compare', 'career-path'],
    relatedBlogSlugs: [],
    demoVariant: 'form',
    categoryId: 'career',
  },
  'offer-compare': {
    headline: 'Offer Comparator',
    tagline: 'Two offers — one clear decision.',
    whatItDoes: 'Compares compensation, growth, and risk factors across multiple offers in plain language.',
    howItWorks: ['Enter details for each offer.', 'AI weighs trade-offs.', 'Get recommendation framework.'],
    whoItsFor: 'Candidates choosing between startup vs MNC or city moves.',
    inputLabel: 'Offer details',
    outputLabel: 'Comparison matrix + recommendation',
    exampleOutput: 'Offer A wins on cash; Offer B on equity and brand — decision tree based on your 3-year goal.',
    seoTitle: 'Job Offer Comparison Tool | MyCVRoast',
    seoDescription: 'Pro offer compare for Indian job seekers.',
    keywords: ['compare job offers', 'offer decision'],
    relatedSlugs: ['salary', 'company-research', 'ninety-days'],
    relatedBlogSlugs: [],
    demoVariant: 'analysis',
    categoryId: 'career',
  },
  'company-research': {
    headline: 'Company Research Brief',
    tagline: 'Walk into interviews knowing the business.',
    whatItDoes: 'Summarises company news, product, culture signals, and smart questions to ask interviewers.',
    howItWorks: ['Enter company name + role.', 'AI builds interview prep brief.', 'Use before onsite.'],
    whoItsFor: 'Final-round candidates who need fast diligence.',
    inputLabel: 'Company + role',
    outputLabel: 'Research brief + questions to ask',
    exampleOutput: 'Recent funding, main product lines, 5 tailored questions for eng manager round.',
    seoTitle: 'Company Research for Interviews | MyCVRoast',
    seoDescription: 'Pro company research brief before your interview.',
    keywords: ['company research interview', 'questions to ask interviewer'],
    relatedSlugs: ['interview-prep', 'salary'],
    relatedBlogSlugs: [],
    demoVariant: 'analysis',
    categoryId: 'career',
  },
  'career-path': {
    headline: 'Career Path Planner',
    tagline: 'Where your CV can go next.',
    whatItDoes: 'Suggests realistic next roles, skills to build, and timeline based on your experience.',
    howItWorks: ['Confirm CV loaded.', 'Pick ambition (IC vs manager, domain).', 'Get 3–5 year path map.'],
    whoItsFor: 'Mid-career professionals planning moves.',
    inputLabel: 'CV + career goal',
    outputLabel: 'Career path map',
    exampleOutput: 'Dev → Senior → Staff path with system design and mentoring milestones.',
    seoTitle: 'AI Career Path Planner | MyCVRoast',
    seoDescription: 'Pro career path planning from your CV.',
    keywords: ['career path planner', 'next job after'],
    relatedSlugs: ['skills-gap', 'salary'],
    relatedBlogSlugs: [],
    demoVariant: 'analysis',
    categoryId: 'career',
  },
  'ninety-days': {
    headline: 'First 90 Days Plan',
    tagline: 'Hit the ground running in a new role.',
    whatItDoes: 'Creates a 30/60/90 day plan tailored to your new job title and company context.',
    howItWorks: ['Enter new role and team context.', 'AI drafts learning and delivery milestones.', 'Share with manager.'],
    whoItsFor: 'New hires and people joining after offer acceptance.',
    inputLabel: 'New role details',
    outputLabel: '30/60/90 day plan',
    exampleOutput: 'Days 1–30: stakeholder map; 31–60: ship small win; 61–90: own metric.',
    seoTitle: 'First 90 Days Plan Generator | MyCVRoast',
    seoDescription: 'Pro 30/60/90 day plan for new jobs.',
    keywords: ['first 90 days plan', '30 60 90 day plan new job'],
    relatedSlugs: ['offer-compare', 'company-research'],
    relatedBlogSlugs: [],
    demoVariant: 'form',
    categoryId: 'career',
  },
  'thank-you': {
    headline: 'Thank-You Email After Interview',
    tagline: 'Send while you\'re still fresh in their mind.',
    whatItDoes: 'Drafts a concise thank-you email referencing specific interview moments and your fit.',
    howItWorks: ['Note who interviewed you and topics discussed.', 'AI drafts email.', 'Send within 24 hours.'],
    whoItsFor: 'Every candidate post-round — free and unlimited.',
    inputLabel: 'Interview notes',
    outputLabel: 'Thank-you email',
    exampleOutput: 'Thanks Sarah — enjoyed discussing the migration project; attaching how my API work maps to your Q3 goal.',
    seoTitle: 'Thank You Email After Interview — Free | MyCVRoast',
    seoDescription: 'Free thank-you email generator after job interviews.',
    keywords: ['thank you email interview', 'post interview email'],
    relatedSlugs: ['follow-up', 'debrief'],
    relatedBlogSlugs: ['how-to-write-cover-letter'],
    demoVariant: 'email',
    categoryId: 'emails',
  },
  'follow-up': {
    headline: 'Interview Follow-Up Email',
    tagline: 'Polite nudge when you haven\'t heard back.',
    whatItDoes: 'Writes follow-up emails that aren\'t pushy — referencing timeline and enthusiasm.',
    howItWorks: ['Enter days since interview and context.', 'AI drafts follow-up.', 'Send from email.'],
    whoItsFor: 'Candidates waiting on HR ghosting.',
    inputLabel: 'Timeline + role context',
    outputLabel: 'Follow-up email',
    exampleOutput: 'Checking in on PM role — still very interested; happy to share additional work samples.',
    seoTitle: 'Interview Follow Up Email — Free | MyCVRoast',
    seoDescription: 'Free follow-up email after no response from recruiter.',
    keywords: ['follow up email after interview'],
    relatedSlugs: ['thank-you', 'rejection'],
    relatedBlogSlugs: [],
    demoVariant: 'email',
    categoryId: 'emails',
  },
  rejection: {
    headline: 'Rejection Reply',
    tagline: 'Stay professional — keep the door open.',
    whatItDoes: 'Drafts gracious replies to rejection emails that preserve network for future roles.',
    howItWorks: ['Paste rejection email or context.', 'AI drafts short reply.', 'Send and move on.'],
    whoItsFor: 'Anyone who wants to reply without burning bridges.',
    inputLabel: 'Rejection context',
    outputLabel: 'Professional reply',
    exampleOutput: 'Thanks for the update — would appreciate feedback if possible; open to future roles on the data team.',
    seoTitle: 'Reply to Job Rejection Email — Free | MyCVRoast',
    seoDescription: 'Free professional rejection reply generator.',
    keywords: ['reply to rejection email', 'job rejection response'],
    relatedSlugs: ['follow-up', 'rejection-analyser'],
    relatedBlogSlugs: [],
    demoVariant: 'email',
    categoryId: 'emails',
  },
  'rejection-analyser': {
    headline: 'Rejection Pattern Analyser',
    tagline: 'Why you keep getting no\'s — honest read.',
    whatItDoes: 'Analyses multiple rejections against your CV and JDs to find recurring gaps.',
    howItWorks: ['Add rejection notes + JDs.', 'AI finds patterns.', 'Get fix roadmap.'],
    whoItsFor: 'Pro users on long job searches needing systemic fixes.',
    inputLabel: 'CV + rejections + JDs',
    outputLabel: 'Pattern report + fixes',
    exampleOutput: '4/5 rejections cite "insufficient leadership" — add people-management bullet; try smaller team lead title.',
    seoTitle: 'Job Rejection Analyser | MyCVRoast',
    seoDescription: 'Pro tool to analyse rejection patterns and improve your CV.',
    keywords: ['why am i not getting interviews', 'rejection analysis'],
    relatedSlugs: ['jd-match', 'cv-rewriter', 'skills-gap'],
    relatedBlogSlugs: [],
    demoVariant: 'analysis',
    categoryId: 'emails',
  },
  resignation: {
    headline: 'Resignation Letter',
    tagline: 'Clean exit — no drama.',
    whatItDoes: 'Generates professional resignation letters with notice period and gratitude.',
    howItWorks: ['Enter dates and tone.', 'AI drafts letter.', 'Send to HR.'],
    whoItsFor: 'Employees resigning in India corporate context.',
    inputLabel: 'Notice period + details',
    outputLabel: 'Resignation letter',
    exampleOutput: 'Standard two-line notice with thank-you paragraph and handover offer.',
    seoTitle: 'Resignation Letter Generator — Free | MyCVRoast',
    seoDescription: 'Free resignation letter generator for Indian employees.',
    keywords: ['resignation letter format india'],
    relatedSlugs: ['thank-you', 'follow-up'],
    relatedBlogSlugs: [],
    demoVariant: 'email',
    categoryId: 'emails',
  },
  'elevator-pitch': {
    headline: 'Elevator Pitch',
    tagline: '30 seconds that actually lands.',
    whatItDoes: 'Creates short and long self-introduction scripts from your CV for networking and interviews.',
    howItWorks: ['Confirm CV.', 'Pick scenario (networking, interview opener).', 'Get scripts + optional read-aloud.'],
    whoItsFor: 'Anyone who freezes on "Tell me about yourself."',
    inputLabel: 'CV + scenario',
    outputLabel: '30s and 60s pitch scripts',
    exampleOutput:
      'Short: backend engineer who scaled payments to 2M daily txns. Long: STAR story variant for "Tell me about yourself."',
    seoTitle: 'Elevator Pitch from Resume — Free | MyCVRoast',
    seoDescription: 'Free elevator pitch generator from your CV.',
    keywords: ['elevator pitch job search', 'tell me about yourself'],
    relatedSlugs: ['interview-prep', 'mock-interview'],
    relatedBlogSlugs: [],
    demoVariant: 'form',
    categoryId: 'extras',
  },
  'scam-detector': {
    headline: 'Job Scam Detector',
    tagline: 'Spot fake recruiters before you share Aadhaar.',
    whatItDoes: 'Analyses suspicious job messages, emails, or WhatsApp offers for red flags common in India.',
    howItWorks: ['Paste message or job ad.', 'AI scores scam likelihood.', 'Get safety checklist.'],
    whoItsFor: 'Freshers targeted by fake WFH and registration-fee scams.',
    inputLabel: 'Job message or ad text',
    outputLabel: 'Scam risk score + red flags',
    exampleOutput: 'High risk: upfront fee, Gmail-only HR, no company domain. Do not pay.',
    seoTitle: 'Job Scam Detector India — Free | MyCVRoast',
    seoDescription: 'Free job scam checker for suspicious offers in India.',
    keywords: ['job scam india', 'fake job offer whatsapp'],
    relatedSlugs: ['company-research', 'cold-email'],
    relatedBlogSlugs: [],
    demoVariant: 'analysis',
    categoryId: 'extras',
  },
  'freelancer-profile': {
    headline: 'Freelancer Profile Writer',
    tagline: 'Upwork/Fiverr bio from your CV.',
    whatItDoes: 'Turns CV experience into freelancer platform bios and service descriptions.',
    howItWorks: ['Paste CV + platform.', 'AI writes bio and service blurbs.', 'Publish on platform.'],
    whoItsFor: 'Side hustlers and freelancers entering gig platforms.',
    inputLabel: 'CV + platform',
    outputLabel: 'Freelancer bio + services',
    exampleOutput: 'Upwork overview highlighting 5 delivered web apps + stack; 3 service titles with deliverables.',
    seoTitle: 'Freelancer Profile from CV | MyCVRoast',
    seoDescription: 'Generate freelancer bios from your resume.',
    keywords: ['freelancer bio generator', 'upwork profile help'],
    relatedSlugs: ['linkedin', 'cv-rewriter'],
    relatedBlogSlugs: ['freelance-jobs-beginners-india'],
    demoVariant: 'form',
    categoryId: 'extras',
  },
}

function categoryForSlug(slug: ToolSlug): string {
  for (const cat of TOOL_CATEGORIES) {
    if (cat.slugs.includes(slug)) return cat.id
  }
  return 'extras'
}

function buildEntry(tool: (typeof DASHBOARD_TOOLS)[number]): CareerToolMarketing {
  const override = CONTENT[tool.slug]
  const catId = override?.categoryId ?? categoryForSlug(tool.slug)
  const freeLabel = toolAccessFreeLabel(tool.access)
  const proLabel = toolAccessProLabel()

  return {
    slug: tool.slug,
    headline: override?.headline ?? tool.label,
    tagline: override?.tagline ?? `AI-powered ${tool.label.toLowerCase()} in your MyCVRoast dashboard.`,
    whatItDoes:
      override?.whatItDoes ??
      `${tool.label} uses your CV and job context to generate tailored output inside the dashboard.`,
    howItWorks: override?.howItWorks ?? [
      'Sign in and open the tool from your dashboard.',
      'Paste or confirm your CV and add job details.',
      'Run the tool and copy or save results.',
    ],
    whoItsFor: override?.whoItsFor ?? 'Job seekers using MyCVRoast for CV, applications, and interviews.',
    inputLabel: override?.inputLabel ?? 'Your CV + job context',
    outputLabel: override?.outputLabel ?? `${tool.label} output`,
    exampleOutput: override?.exampleOutput ?? 'Structured AI output you can copy into applications or prep notes.',
    freeVsPro: tool.access.proOnly
      ? `Pro only — ${proLabel} with Pro plan.`
      : `Free: ${freeLabel}. Pro: ${proLabel}.`,
    dashboardHref: tool.href,
    seoTitle: override?.seoTitle ?? `${tool.label} — AI Career Tool | MyCVRoast`,
    seoDescription:
      override?.seoDescription ??
      `Use ${tool.label} on MyCVRoast — ${freeLabel}. Built for Indian job seekers.`,
    keywords: override?.keywords ?? [tool.label.toLowerCase(), 'mycvroast', 'career ai tool'],
    relatedSlugs:
      override?.relatedSlugs ??
      (TOOL_CATEGORIES.find((c) => c.id === catId)?.slugs.filter((s) => s !== tool.slug).slice(0, 3) ?? []),
    relatedBlogSlugs: override?.relatedBlogSlugs ?? [],
    demoVariant: override?.demoVariant ?? 'default',
    categoryId: catId,
  }
}

export const CAREER_TOOL_MARKETING: CareerToolMarketing[] = DASHBOARD_TOOLS.map(buildEntry)

export function getCareerToolMarketing(slug: string): CareerToolMarketing | undefined {
  return CAREER_TOOL_MARKETING.find((t) => t.slug === slug)
}

export function getAllCareerToolSlugs(): ToolSlug[] {
  return DASHBOARD_TOOLS.map((t) => t.slug)
}

export function getCareerToolsByCategory(categoryId: string): CareerToolMarketing[] {
  return CAREER_TOOL_MARKETING.filter((t) => t.categoryId === categoryId)
}

export { TOOL_CATEGORIES as CAREER_TOOL_CATEGORIES }
